config/routes.rb
Rails.application.routes.draw do
  scope '', as: 'kitten_plugin' do
    scope 'projects/:project_id', as: 'project' do
      resources :kittens
    end
  end

  # Create a route that is handled completely in the frontend
  # with a helper controller that just renders a plain page for the frontend
  # to hook into with its own route
  get '/angular_kittens', to: 'angular#empty_layout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, uniqueness: true, length: { minimum: 5 }
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  # Check for the permissions of the user
  # as defined in the engine.rb permissions block
  before_action :find_project_by_project_id
  before_action :authorize

  def index
    @kittens = Kitten.all

    render layout: true
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      # notify_changed_kittens(:created, @kitten)
      flash[:notice] = 'Created new kitten'
      redirect_to action: 'index'
    else
      flash[:error] = 'Cannot create new kitten'
      render action: 'new'
    end
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name)
  end

  # def notify_changed_kittens(action, changed_kitten)
  #   OpenProject::Notifications.send(:kittens_changed, action: action, kitten: changed_kitten)
  # end
end

app/views/homescreen/blocks/_homescreen_block.html.erb
<h3 class="widget-box--header" id="proto-plugin-block">
  <%= op_icon('icon-context icon-cart') %>
  <span class="widget-box--header-title"><%= t(:proto_plugin_name) %></span>
</h3>

<p class="widget-box--additional-info">A bunch of cute kittens from which to choose.</p>

<ul class="widget-box--arrow-links">
  <li>
    <%= link_to t(:label_kittens),
                kitten_plugin_project_kittens_path(project_id: Project.first.identifier),
                title: t(:label_kittens) %>
  </li>
</ul>

<div class="widget-box--blocks--buttons">
  <% if User.current.allowed_in_any_project?(:manage_kittens) %>
    <%= link_to new_kitten_plugin_project_kitten_path(project_id: Project.first.identifier), {
      class: 'button -alt-highlight',
      aria: {label: t(:label_kitten_new)},
      title: t(:label_kitten_new)
    } do %>
      <%= op_icon('button--icon icon-add') %>
      <span class="button--text"><%= t(:label_kitten) %></span>
    <% end %>
  <% end %>
</div>

app/views/hooks/proto_plugin/_homescreen_after_links.html.erb
<section class="widget-boxes -flex" id="homescreen-after-links">
  <div class="widget-box">
    <h3 class="widget-box--header">
      <%= op_icon('icon-context icon-user') %>
      <span class="widget-box--header-title">:homescreen_after_links hook</span>
    </h3>

    <ul class="widget-box--arrow-links">
      <li>For kittens go <%= link_to "here", angular_kittens_path %>.</li>
    </ul>
  </div>
</section>

app/views/hooks/proto_plugin/_view_layouts_base_sidebar.html.erb
<p style="color: red;">
  :view_layouts_base_sidebar hook
</p>

app/views/kittens/_form.html.erb
<%= labelled_tabular_form_for(kitten, url: { action: kitten.new_record? ? :create : :update }) do |f| %>

<%= error_messages_for kitten %>

<section class="form--section">
  <div class="form--field -required">
    <%= f.text_field :name, required: true %>
  </div>

    <div class="widget-box--blocks--buttons">
        <button type="submit" class="button -alt-highlight" title="New Kitten">
            <span class="button--text"><%= t(:button_create) %></span>
        </button>
    </div>
</section>

<% end %>

app/views/kittens/index.html.erb
<% html_title t(:label_kittens) %>


<%= toolbar(title: t(:label_kittens)) do %>
  <% if (@project.present? && current_user.allowed_in_project?(:manage_kittens, @project)) || (@project.nil? && current_user.allowed_in_any_project?(:manage_kittens)) %>
    <li class="toolbar-item">
      <%= link_to(new_kitten_plugin_project_kitten_path, class: 'button') do %>
        <span class="button--text"><%= t(:label_kitten_new) %></span>
      <% end %>
    </li>
  <% end %>
<% end %>


<% if @kittens.empty? %>
  <%= no_results_box %>
<% else %>
  <p>
    These are the kittens:
  </p>
  <% @kittens.each do |kitten| %>
    <%= tag 'kitten-component', data: { 'kitten-name': kitten.name } %>
  <% end %>
<% end %>


<%= render "shared/kitty_image" %>

app/views/kittens/new.html.erb
<% html_title t(:label_kitten_new) %>

<h1><%= t(:label_kitten_new) %></h1>

<%= render "form", kitten: @kitten %>

<%= render "shared/kitty_image" %>

app/views/shared/_kitty_image.html.erb
<div class="kitty-image">
  <%= image_tag 'kitty.png' %>
</div>